//
//  Constants.h
//  iPadAppELC
//
//  Created by Hitesh Merchant on 12/6/10.
//  Copyright 2010 __MyCompanyName__. All rights reserved.
//

#import <Foundation/Foundation.h>

/*
NSString *const striPhoneSimulator;
NSString *const striPadSimulator;
NSString *const striPhone;
NSString *const striPad;
NSString *const striPod;
*/

NSString *const strADFS_TO;
NSString *const strADFS_APPLY_TO;
NSString *const strADFS_END_POINT_URL;

NSString *const strAPI_AUTH_TOKEN;
NSString *const strAPI_URL;

NSString *const strAPI_BATCH_GET_VERSION_LIST;
NSString *const strAPI_BATCH_GET_CONVERGENCE_DTL;

NSString *const strAPI_ATTENDEE_VALIDATE_DOMAIN_ATTENDEE;
NSString *const strAPI_ATTENDEE_VALIDATE_MS_ATTENDEE;

NSString *const strAPI_SPONSOR_GET_SPONSOR_LIST;

NSString *const strAPI_VENUE_GET_VENUE_LIST;

NSString *const strAPI_CONFERENCE_GET_CONFERENCE_LIST;
NSString *const strAPI_CONFERENCE_GET_AGENDA_LIST;

NSString *const strAPI_CONFERENCE_GET_Shuttle_LIST;

NSString *const strAPI_ATTENDEE_GET_ATTENDEE_LIST;
NSString *const strAPI_ATTENDEE_SET_PRIVACY;
NSString *const strAPI_ATTENDEE_GET_PRIVACY;
NSString *const strAPI_ATTENDEE_GET_MESSAGING_LIST;
NSString *const strAPI_ATTENDEE_ADD_MESSAGE;
NSString *const strAPI_ATTENDEE_DELETE_INBOX_MESSAGE;
NSString *const strAPI_ATTENDEE_DELETE_SENTBOX_MESSAGE;
NSString *const strAPI_ATTENDEE_AskToSpeakers;
NSString *const strAPI_ATTENDEE_GET_ATTENDEE_FAV_LIST;

NSString *const strAPI_SESSION_GET_SESSION_LIST;
NSString *const strAPI_SESSION_GET_SPEAKER_LIST;
NSString *const strAPI_SESSION_GET_TRACKS_LIST;
NSString *const strAPI_SESSION_GET_SUB_TRACKS_LIST;
NSString *const strAPI_SESSION_GET_CATEGORY_LIST;
NSString *const strAPI_SESSION_GET_ROOMS_LIST;
NSString *const strAPI_SESSION_GET_MY_SESSION_LIST;
NSString *const strAPI_SESSION_ADD_MY_SESSION_LIST;
NSString *const strAPI_SESSION_GET_FILTER_LIST;
NSString *const strAPI_SESSION_SYNC_MY_SESSION_LIST;
NSString *const strAPI_ATTENDEE_SAVE_FAV_ATTENDEE;
NSString *const strAPI_ATTENDEE_DELETE_FAV_ATTENDEE;


NSString *const strAPI_EXHIBITOR_GET_EXHIBITOR_LIST;
NSString *const strAPI_EXHIBITOR_GET_ATTENDEE_EXHIBITOR_LIST;
NSString *const strAPI_EXHIBITOR_ADD_EXHIBITOR;
NSString *const strAPI_EXHIBITOR_DELETE_EXHIBITOR;
NSString *const strAPI_EXHIBITOR_DELETE_EXHIBITOR_BY_CODE;

NSString *const strAPI_EVENT_INFO_GET_EMERGENCY_LIST;
NSString *const strAPI_EVENT_INFO_GET_SHUTTLE_SCHEDULE_LIST;
NSString *const strAPI_EVENT_INFO_GET_LOST_FOUND_LIST;
NSString *const strAPI_EVENT_INFO_GET_FAQ_LIST;
NSString *const strAPI_EVENT_INFO_GET_ONSITE_SERVICE_LIST;
NSString *const strAPI_EVENT_INFO_GET_DETAIL_LIST;
NSString *const strAPI_EVENT_INFO_GET_CATEGORY_LIST;

NSString *const strAPI_NOTES_ADD_NOTE;
NSString *const strAPI_NOTES_GET_SESSION_NOTES_LIST;
NSString *const strAPI_NOTES_GET_USER_NOTES_LIST;

NSString *const strAPI_NOTES_ADD_ATTENDEE_NOTES;
NSString *const strAPI_NOTES_DELETE_ATTENDEE_NOTES;
NSString *const strAPI_NOTES_SYNC_ATTENDEE_NOTES;

NSString *const strAPI_PHOTOS_UPLOAD;
NSString *const strAPI_PHOTOS_UPLOAD_THUMB;
NSString *const strAPI_PHOTOS_GET_RECENT_FOR_DASHBOARD;
NSString *const strAPI_PHOTOS_GET_SEARCH_PHOTO;
NSString *const strAPI_PHOTOS_GET_RECENT_PHOTO;
NSString *const strAPI_PHOTOS_GET_POPULAR_PHOTO;
NSString *const strAPI_PHOTOS_DELETE_PHOTO;
NSString *const strAPI_PHOTOS_ADD_PHOTO_LIKE;
NSString *const strAPI_PHOTOS_UPDATE_PHOTO_LIKE;
NSString *const strAPI_OLD_PHOTOS_UPLOAD;
NSString *const strAPI_OLD_PHOTOS_UPLOAD_THUMB;
NSString *const strAPI_PHOTOS_USERWISE_UPLOAD;
NSString *const strAPI_PHOTOS_GET_UPLOADS;
NSString *const strAPI_PHOTOS_ADD_PHOTO_COMMENT;
NSString *const strAPI_PHOTOS_GET_PHOTO_COMMENT_LIST;
NSString *const strAPI_PHOTOS_GET_PHOTO_LIKES_COMMENTS_COUNT;
NSString *const strAPI_PHOTOS_GET_PHOTO_LIKE_STATUS;
NSString *const strAPI_PHOTOS_GET_SEARCH_PHOTO_USERWISE;
NSString *const strAPI_PHOTOS_GET_SEARCH_PHOTO_HASHTAG;

NSString *const strAPI_ANNOUNCEMENT_GET_ANNOUNCEMENT_LIST;

NSString *const strAPI_ANALYITC_ADD_ANALYTIC;
NSString *const strAPI_ERROR_LOG_ERROR;

NSString *const strLIVESDK_INIT;
NSString *const strLIVESDK_LOGIN;
NSString *const strLIVESDK_LOGOUT;
NSString *const strLIVESDK_GETME;

typedef enum OperConstants
{
    OPER_VALIDATE_DOMAIN_ATTENDEE = 1,
    OPER_VALIDATE_MS_ATTENDEE = 2,
    OPER_GET_SPONSOR_LIST = 3,
    OPER_GET_SPEAKER_LIST = 4,
    OPER_GET_VENUE_LIST = 5,
    OPER_GET_AGENDA_LIST = 6,
    OPER_GET_SHUTTLE_LIST = 64,
    OPER_GET_ANTENDEE_LIST = 7,
    OPER_SET_PRIVACY = 8,
    OPER_GET_PRIVACY = 9,
    OPER_GET_SESSION_LIST = 10,
    OPER_GET_EXHIBITOR_LIST = 11,
    OPER_GET_CONFERENCE_LIST = 12,
    OPER_GET_EMERGENCY_LIST = 13,
    OPER_GET_SHUTTLE_SERVICE_LIST = 14,
    OPER_GET_LOST_FOUND_LIST = 15,
    OPER_GET_FAQ_LIST = 16,
    OPER_GET_ONSITE_SERVICE_LIST = 17,
    OPER_GET_EVENT_INFO_DTL_LIST = 18,
    OPER_GET_EVENT_INFO_CATEGORY_LIST = 19,
    OPER_GET_TRACKS_LIST = 20,
    OPER_GET_SUB_TRACKS_LIST = 21,
    OPER_GET_CATEGORY_LIST = 22,
    OPER_GET_ROOMS_LIST = 23,
    OPER_GET_MY_SESSION_LIST = 24,
    OPER_ADD_MY_SESSION_LIST = 25,
    OPER_REMOVE_MY_SESSION_LIST = 26,
    OPER_GET_USER_NOTES_LIST = 27,
    OPER_ADD_NOTE_LIST = 28,
    OPER_ADFS_LOGON = 29,
    OPER_GET_ATTENDEE_EXHIBITOR_LIST = 30,
    OPER_ADD_EXHIBITOR = 31,
    OPER_DELETE_EXHIBITOR = 32,
    OPER_GET_FILTER_LIST = 33,
    OPER_GET_ANNOUNCEMENT_LIST = 34,
    OPER_PHOTOS_UPLOAD = 35,
    OPER_PHOTOS_UPLOAD_THUMB = 36,
    OPER_PHOTOS_GET_RECENT_FOR_DASHBOARD = 37,
    OPER_PHOTOS_GET_SEARCH_PHOTO = 38,
    OPER_PHOTOS_GET_RECENT_PHOTO = 39,
    OPER_PHOTOS_ADD_PHOTO_LIKE = 40,
    OPER_PHOTOS_USERWISE_UPLOAD= 41,
    OPER_PHOTOS_GET_UPLOADS= 42,
    OPER_PHOTOS_GET_POPULAR_PHOTO = 43,
    OPER_SYNC_MY_SESSION_LIST = 44,
    OPER_ADD_ANALYTIC = 45,
    OPER_GET_MESSAGING_LIST = 46,
    OPER_ADD_MESSAGE = 47,
    OPER_PHOTOS_ADD_PHOTO_COMMENT = 48,
    OPER_PHOTOS_GET_PHOTO_COMMENT_LIST = 49,
    OPER_PHOTOS_GET_PHOTO_LIKES_COMMENTS_COUNT = 50,
    OPER_PHOTOS_UPDATE_PHOTO_LIKE = 51,
    OPER_PHOTOS_GET_PHOTO_LIKE_STATUS = 52,
    OPER_PHOTOS_GET_SEARCH_PHOTO_USERWISE = 53,
    OPER_PHOTOS_GET_SEARCH_PHOTO_HASHTAG = 54,
    OPER_ATTENDEE_DELETE_INBOX_MESSAGE = 55,
    OPER_ATTENDEE_DELETE_SENTBOX_MESSAGE = 56,
    OPER_PHOTOS_DELETE_PHOTO = 57,
    OPER_LOG_ERROR = 58,
    OPER_DELETE_EXHIBITOR_BY_CODE = 59,
    OPER_GET_EVENT_INFO_DETAILS = 60,
    OPER_BATCH_GET_VERSION_LIST = 1001,
    OPER_BATCH_GET_CONVERGENCE_DTL = 1002,
    OPER_FB_GETUSER_INFO = 2001,
    OPER_FB_GETUSER_PICTURE = 2002,
    OPER_FB_GETUSER_FRIENDS = 2003,
    OPER_FB_PUBLISH = 2004,
}OperConstants;

NSString *const strAPP_SETTINGS_SET_PRIVACY;
NSString *const strAPP_SETTINGS_LIVEID_AUTHENTICATION_TOKEN;
NSString *const strAPP_SETTINGS_LIVEID_LINK;
NSString *const strAPP_SETTINGS_ACCOUNT_EMAIL;
NSString *const strAPP_SETTINGS_PUID;
NSString *const strAPP_SETTINGS_PRIMARY_GROUP_SID;
NSString *const strAPP_SETTINGS_PRIMARY_SID;
NSString *const strAPP_SETTINGS_ALIAS;
NSString *const strAPP_SETTINGS_UPN;
NSString *const strAPP_SETTINGS_USE_BATCH_UPDATE;

NSString *const strLIVESDK_CLIENT_ID;
NSString *const strLIVESDK_SCOPES;

NSString *const strKEY_VERSION_NO;

NSString *const strDOC_TYPE_PDF_IMG;
NSString *const strDOC_TYPE_DOC_IMG;
NSString *const strDOC_TYPE_XLS_IMG;
NSString *const strDOC_TYPE_PPT_IMG;

NSString *const strDOC_TYPE_PDF;
NSString *const strDOC_TYPE_DOC;
NSString *const strDOC_TYPE_DOCX;
NSString *const strDOC_TYPE_XLS;
NSString *const strDOC_TYPE_XLSX;
NSString *const strDOC_TYPE_PPT;
NSString *const strDOC_TYPE_PPTX;

NSUInteger const intEVENT_INFO_CATEGORY_ONSITE_SERVICES;
NSUInteger const intEVENT_INFO_CATEGORY_ATTENDEE_MEALS;
NSUInteger const intEVENT_INFO_CATEGORY_SPEACIALTY_MEALS;
NSUInteger const intEVENT_INFO_CATEGORY_CONFERENCE_SECURITY;
NSUInteger const intEVENT_INFO_CATEGORY_LUGGAGE;
NSUInteger const intEVENT_INFO_CATEGORY_MS_IT_TECH_LINKS;
NSUInteger const intEVENT_INFO_CATEGORY_FAQ;
NSUInteger const intEVENT_INFO_CATEGORY_MEALS;

NSString *const strEVENT_INFO_CATEGORY_ONSITE_SERVICES;
NSString *const strEVENT_INFO_CATEGORY_ATTENDEE_MEALS;
NSString *const strEVENT_INFO_CATEGORY_SPEACIALTY_MEALS;
NSString *const strEVENT_INFO_CATEGORY_CONFERENCE_SECURITY;
NSString *const strEVENT_INFO_CATEGORY_LUGGAGE;
NSString *const strEVENT_INFO_CATEGORY_MS_IT_TECH_LINKS;
NSString *const strEVENT_INFO_CATEGORY_FAQ;
NSString *const strEVENT_INFO_CATEGORY_MEALS;

NSString *const strAPI_BATCH_GET_EventInfoBatchDetails;

NSString *const strAPI_EVALUATION_GETEVALUATIONLIST;
NSString *const strAPI_EVALUATION_GETOVERALLEVALUATIONLIST;
NSString *const strAPI_EVALUATION_GETSESSIONWISEEVALUATIONLIST;
NSString *const strAPI_EVALUATION_GETEVALUATIONLISTBYSESSIONINSTANCEID;
NSString *const strAPI_EVALUATION_GETEVALUATIONLISTBYCATEGORYINSTANCEID;
NSString *const strAPI_EVALUATION_SUBMITEVALUATION;

NSString *const strUSER_DEFAULT_KEY_USER_INFO;

NSString *const strSCREEN_AGENDA;
NSString *const strSCREEN_ANNOUNCEMENT;
NSString *const strSCREEN_ATTENDEE;
NSString *const strSCREEN_ATTENDEE_EXHIBITOR;
NSString *const strSCREEN_CATEGORIES;
NSString *const strSCREEN_CONFERENCE;
NSString *const strSCREEN_CONFERENCE_AGENDA;
NSString *const strSCREEN_EMERGENCY;
NSString *const strSCREEN_EVALUATION;
NSString *const strSCREEN_EVENT_INFO_CATEGORIES;
NSString *const strSCREEN_EVENT_INFO_DTL;
NSString *const strSCREEN_EXHIBITOR;
NSString *const strSCREEN_FAQ;
NSString *const strSCREEN_FILTER;
NSString *const strSCREEN_LOST_FOUND;
NSString *const strSCREEN_MY_CONFERENCE;
NSString *const strSCREEN_MY_SCHEDULE;
NSString *const strSCREEN_ONSITE_SERVICE;
NSString *const strSCREEN_PHOTO;
NSString *const strSCREEN_ROOMS;
NSString *const strSCREEN_SESSION;
NSString *const strSCREEN_SPEAKER;
NSString *const strSCREEN_SPONSOR;
NSString *const strSCREEN_SUB_TRACK;
NSString *const strSCREEN_TRACK;
NSString *const strSCREEN_USER_NOTE;
NSString *const strSCREEN_VENUE;
NSString *const strSCREEN_SHUTTLE;

NSString *const strSCREEN_MEALS;
NSString *const strSCREEN_EXPO_MAPS;

NSString *const strSCREEN_HAPPENING_NOW;

NSString *const strSCREEN_SOCIAL_MEDIA;
NSString *const strSCREEN_SOCIAL_MEDIA_LINKEDIN;
NSString *const strSCREEN_SOCIAL_MEDIA_FACEBOOK;
NSString *const strSCREEN_SOCIAL_MEDIA_TWITTER;

NSString *const strSCREEN_INTERNET_ACCESS;
NSString *const strSCREEN_CITY_GUIDE;
NSString *const strSCREEN_CITY_GUIDE_MAP;
NSString *const strSCREEN_SYNC_UP;
NSString *const strSCREEN_LOGON;
NSString *const strSCREEN_ADFS_LOGON;
NSString *const strSCREEN_SETTINGS;
NSString *const strSCREEN_GLOBAL_SEARCH;

NSString *const strSCREEN_ABOUTUS;
NSString *const strSCREEN_CONTACTUS;
NSString *const strSCREEN_SUPPORT;
NSString *const strSCREEN_MDPN;
NSString *const strSCREEN_TERMS;
NSString *const strSCREEN_PRIVACY_POLICY;

NSString *const strAPI_ATTENDEE_SEARCH_ATTENDEE;


NSString *const strSCREEN_HOME;

NSString *const strNoInternetError;

@interface Constants : NSObject
@end
